/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardProductsRouteRouteImport } from './routes/dashboard/products/route'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/dashboard/categories/index'
import { Route as DashboardBusinessSettingsRouteImport } from './routes/dashboard/business/settings'
import { Route as DashboardBusinessLimitsRouteImport } from './routes/dashboard/business/limits'
import { Route as DashboardBusinessInfoRouteImport } from './routes/dashboard/business/info'
import { Route as AuthGoogleErrorRouteImport } from './routes/auth/google/error'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsRouteRoute = DashboardProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBusinessSettingsRoute =
  DashboardBusinessSettingsRouteImport.update({
    id: '/business/settings',
    path: '/business/settings',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBusinessLimitsRoute = DashboardBusinessLimitsRouteImport.update({
  id: '/business/limits',
  path: '/business/limits',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBusinessInfoRoute = DashboardBusinessInfoRouteImport.update({
  id: '/business/info',
  path: '/business/info',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthGoogleErrorRoute = AuthGoogleErrorRouteImport.update({
  id: '/auth/google/error',
  path: '/auth/google/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/products': typeof DashboardProductsRouteRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/error': typeof AuthGoogleErrorRoute
  '/dashboard/business/info': typeof DashboardBusinessInfoRoute
  '/dashboard/business/limits': typeof DashboardBusinessLimitsRoute
  '/dashboard/business/settings': typeof DashboardBusinessSettingsRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/products': typeof DashboardProductsRouteRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/error': typeof AuthGoogleErrorRoute
  '/dashboard/business/info': typeof DashboardBusinessInfoRoute
  '/dashboard/business/limits': typeof DashboardBusinessLimitsRoute
  '/dashboard/business/settings': typeof DashboardBusinessSettingsRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/products': typeof DashboardProductsRouteRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/error': typeof AuthGoogleErrorRoute
  '/dashboard/business/info': typeof DashboardBusinessInfoRoute
  '/dashboard/business/limits': typeof DashboardBusinessLimitsRoute
  '/dashboard/business/settings': typeof DashboardBusinessSettingsRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/products'
    | '/dashboard/orders'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/auth/google/callback'
    | '/auth/google/error'
    | '/dashboard/business/info'
    | '/dashboard/business/limits'
    | '/dashboard/business/settings'
    | '/dashboard/categories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/products'
    | '/dashboard/orders'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard'
    | '/auth/google/callback'
    | '/auth/google/error'
    | '/dashboard/business/info'
    | '/dashboard/business/limits'
    | '/dashboard/business/settings'
    | '/dashboard/categories'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/products'
    | '/dashboard/orders'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/auth/google/callback'
    | '/auth/google/error'
    | '/dashboard/business/info'
    | '/dashboard/business/limits'
    | '/dashboard/business/settings'
    | '/dashboard/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthGoogleErrorRoute: typeof AuthGoogleErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/business/settings': {
      id: '/dashboard/business/settings'
      path: '/business/settings'
      fullPath: '/dashboard/business/settings'
      preLoaderRoute: typeof DashboardBusinessSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/business/limits': {
      id: '/dashboard/business/limits'
      path: '/business/limits'
      fullPath: '/dashboard/business/limits'
      preLoaderRoute: typeof DashboardBusinessLimitsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/business/info': {
      id: '/dashboard/business/info'
      path: '/business/info'
      fullPath: '/dashboard/business/info'
      preLoaderRoute: typeof DashboardBusinessInfoRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/google/error': {
      id: '/auth/google/error'
      path: '/auth/google/error'
      fullPath: '/auth/google/error'
      preLoaderRoute: typeof AuthGoogleErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardProductsRouteRoute: typeof DashboardProductsRouteRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBusinessInfoRoute: typeof DashboardBusinessInfoRoute
  DashboardBusinessLimitsRoute: typeof DashboardBusinessLimitsRoute
  DashboardBusinessSettingsRoute: typeof DashboardBusinessSettingsRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProductsRouteRoute: DashboardProductsRouteRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBusinessInfoRoute: DashboardBusinessInfoRoute,
  DashboardBusinessLimitsRoute: DashboardBusinessLimitsRoute,
  DashboardBusinessSettingsRoute: DashboardBusinessSettingsRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthGoogleErrorRoute: AuthGoogleErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
